version: '3.9'

services:
  pic_main:
    build: .
    environment:
      - EMAIL=draste@imola.io
      - PIC_DOMAIN=cars.imola.io
      - MAIN_DOMAIN=cars.imola.io
      - MAIN_HOST=cars.imola.io
      - ALBUM_LIST_PATH=/data/pics/sys/album-data/album-list.txt
      - PIC_SERVER_PORT=3000
    restart: always
    volumes:
      - /home/dns/imola.io/pic-project:/app
      - /app/node_modules
      - /home/dns/imola.io/auto:/data/pics/auto
      - /home/dns/imola.io/auto-prv:/data/pics/auto-prv
      - /home/dns/imola.io/album-data:/data/pics/sys/album-data
      - /home/dns/imola.io/express-logs:/app/logs
    ports:
      - "3000:3000"
