version: '3.9'

services:
  pic_main:
    build: .
    container_name: pic_main
    environment:
      - EMAIL=${EMAIL}
      - PIC_DOMAIN=${PIC_DOMAIN}
      - MAIN_DOMAIN=${MAIN_DOMAIN}
      - MAIN_HOST=${MAIN_HOST}
      - ALBUM_LIST_PATH=${ALBUM_LIST_PATH}
      - PIC_SERVER_PORT=${PIC_SERVER_PORT}
    restart: always
    volumes:
      - /data/pics/auto:/data/pics/auto
      - /data/pics/auto-prv:/data/pics/auto-prv
      - /data/pics/sys/album-data:/data/pics/sys/album-data
      - /data/pics/sys/http-data:/data/pics/sys/http-data
      - /data/pics/sys/express-logs:/app/logs
      - /srv/pic-project/public:/app/public
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.express-service.rule=Host(`${PIC_DOMAIN}`)
      - traefik.http.routers.express-service.service=express-service
      - traefik.http.routers.express-service.entrypoints=web
      - traefik.http.routers.express-serviceSecure.rule=Host(`${PIC_DOMAIN}`)
      - traefik.http.routers.express-serviceSecure.service=express-service
      - traefik.http.routers.express-serviceSecure.entrypoints=webSecure
      - traefik.http.routers.express-serviceSecure.tls.certresolver=letsEncrypt

      - traefik.http.middlewares.express-header.headers.FrameDeny=true
      - traefik.http.middlewares.express-header.headers.browserXssFilter=true
      - traefik.http.middlewares.express-header.headers.contentTypeNosniff=true
      - traefik.http.middlewares.express-header.headers.stsSeconds=315360000
      - traefik.http.middlewares.express-header.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.express-header.headers.stsPreload=true

      - traefik.http.middlewares.https-redirect.redirectScheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectScheme.permanent=true

      - traefik.http.middlewares.compress.compress=true

      - traefik.http.routers.express-service.middlewares=express-header@docker,https-redirect@docker,compress@docker
      - traefik.http.routers.express-serviceSecure.middlewares=express-header@docker,https-redirect@docker,compress@docker

      - traefik.http.services.express-service.loadbalancer.server.port=${PIC_SERVER_PORT}

networks:
  traefik:
    external: true
    name: traefik