version: '3.9'

services:
  pic_main:
    build: .
    image: "ghcr.io/spotemkin/pictures:latest"
    environment:
      - EMAIL=draste@imola.io
      - PIC_DOMAIN=cars.imola.io
      - MAIN_DOMAIN=cars.imola.io
      - MAIN_HOST=cars.imola.io
      - ALBUM_LIST_PATH=/data/pics/sys/album-data/album-list.txt
      - PIC_SERVER_PORT=3000
    restart: always
    volumes:
      - /home/dns/imola.io/auto:/data/pics/auto
      - /home/dns/imola.io/auto-prv:/data/pics/auto-prv
      - /home/dns/imola.io/album-data:/data/pics/sys/album-data
      - /home/dns/web/cars.imola.io/public_html:/data/pics/sys/http-data
      - /home/dns/imola.io/express-logs:/app/logs
      - /home/dns/web/cars.imola.io/public_html:/app/public
    ports:
      - "3000:3000"
    user: "dns"
    deploy:
      replicas: 8
      update_config:
        parallelism: 2
        delay: 10s