version: '3.9'

services:
  picmain:
    build: .
    container_name: picmain
    restart: always
    volumes:
      - /data/pics/auto:/data/pics/auto
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik