name: Deploy PIC to PROD

on:
  workflow_dispatch:

# env:
  # ALBUM_LIST_PATH: ${{ secrets.ALBUM_LIST_PATH }}
  # PIC_CLIENT_PORT: ${{ secrets.PIC_CLIENT_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: prod

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: List files
        run: ls -l

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            type=sha

      - name: Build and push pic-main
        env:
          ALBUM_LIST_PATH: ${{ vars.ALBUM_LIST_PATH }}
          PIC_CLIENT_PORT: ${{ vars.PIC_CLIENT_PORT }}
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ALBUM_LIST_PATH=${{ vars.ALBUM_LIST_PATH }}
            PIC_CLIENT_PORT=${{ vars.PIC_CLIENT_PORT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true

      - name: Copy Docker and docker-compose files to server
        env:
          ALBUM_LIST_PATH: ${{ vars.ALBUM_LIST_PATH }}
          PIC_CLIENT_PORT: ${{ vars.PIC_CLIENT_PORT }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.MAIN_DOMAIN }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          source: "Dockerfile, docker-compose-prod.yaml"
          target: /srv/pic-project
          overwrite: true
          debug: true

      - name: Copy public folder to server
        env:
          ALBUM_LIST_PATH: ${{ vars.ALBUM_LIST_PATH }}
          PIC_CLIENT_PORT: ${{ vars.PIC_CLIENT_PORT }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.MAIN_DOMAIN }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          source: "public"
          target: /data/pics/sys/nginx-data
          overwrite: true
          debug: true

      - name: Docker compose up
        env:
          ALBUM_LIST_PATH: ${{ vars.ALBUM_LIST_PATH }}
          PIC_CLIENT_PORT: ${{ vars.PIC_CLIENT_PORT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.MAIN_DOMAIN }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          script: |
            cd /srv/pic-project
            export EMAIL=${{ vars.EMAIL }}
            export PIC_HOST=${{ vars.PIC_HOST }}
            export MAIN_DOMAIN=${{ vars.MAIN_DOMAIN }}
            export ALBUM_LIST_PATH=${{ vars.ALBUM_LIST_PATH }}
            export PIC_CLIENT_PORT=${{ vars.PIC_CLIENT_PORT }}
            docker-compose -f docker-compose-prod.yaml pull
            docker-compose -f docker-compose-prod.yaml down
            docker-compose -f docker-compose-prod.yaml up -d

